version: '3.8'

services:
  # ---------------------------------------------
  # 1. The Cloud Server running the Head Model
  # ---------------------------------------------
  fsl-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fsl-server
    # Run our hello world server script natively
    command: uv run python src/nodes/server_node.py
    # Expose the gRPC port so tests from our host machine could theoreticall hit it
    ports:
      - "50051:50051"
    # Ensure stdout prints immediately to the compose logs 
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=
    volumes:
      - .:/app
      - /app/.venv
      - ./results:/app/results
    healthcheck:
      # Use python with grpc to test if the port is open and responding
      test: [ "CMD-SHELL", "uv run python -c \"import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.settimeout(1); s.connect(('127.0.0.1', 50051)); s.close()\" || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 2s

  # ---------------------------------------------
  # 2. The Edge Client running the ClientLSTM
  # ---------------------------------------------
  fsl-client:
    build:
      context: .
      dockerfile: Dockerfile
    # Run the client script that establishes the ping
    # command: uv run python src/nodes/client_node.py
    command: uv run python src/nodes/client_node.py ${CLIENT_ID}
    # Don't start the client until the server container is up AND healthy
    depends_on:
      fsl-server:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=
      - CLIENT_ID=${CLIENT_ID}
    # For Phase 5: Map the local dataset folder into the client container
    volumes:
      - .:/app
      - /app/.venv
      - ./dataset:/app/dataset
      - ./results:/app/results
    working_dir: /app
