[clients]
pi01 ansible_host=192.168.3.9  client_id=1
pi02 ansible_host=192.168.3.10 client_id=2
pi03 ansible_host=192.168.3.11 client_id=3
pi04 ansible_host=192.168.3.13 client_id=4
pi05 ansible_host=192.168.3.14 client_id=5
pi06 ansible_host=192.168.3.15 client_id=6
pi07 ansible_host=192.168.3.16 client_id=7
pi08 ansible_host=192.168.3.17 client_id=8
pi09 ansible_host=192.168.3.18 client_id=9
pi10 ansible_host=192.168.3.19 client_id=10
pi11 ansible_host=192.168.3.20 client_id=11

[clients:vars]
ansible_user=pi
ansible_ssh_private_key_file=~/.ssh/id_rsa
